version: '3'

services: 

  db:
    image: postgres:14.5-alpine
    volumes:
      - ./db/twitter-clone.sql:/docker-entrypoint-initdb.d/twitter-clone.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - database_network
    restart: always
    env_file:
      - app/.env

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: twitter-clone
    ports:
      - 8080:8080
    restart: always
    networks:
      - nginx_network
      - database_network
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - nginx_network
    depends_on:
      - app

networks:
  database_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  db_data:
