version: '3'

services: 

  db:
    image: postgres:14.5-alpine
    volumes:
      - db_data:/db/twitter-clone.sql
    env_file:
      - env

  app:
    image: twitter-clone:latest
    volumes:
      - .:/app/
    env_file:
      - env
    networks:
      - app1_network
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app1_network
    depends_on:
      - app

networks:
  database1_network:
    driver: bridge
  app1_network:
    driver: bridge

volumes:
  db_data:
