version: '3'

services: 

  db:
    image: postgres:14.5-alpine
    volumes:
      - db_data:./db/twitter-clone.sql
    env_file:
      - env

  twitter-clone:
    image: twitter-clone:latest
    networks:
      - database1_network
      - nginx_network
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_network
    depends_on:
      - twitter-clone

networks:
  database1_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  db_data:
