version: '3'

services: 

  db:
    image: postgres:14.5-alpine
    volumes:
      - ./db/twitter-clone.sql:/docker-entrypoint-initdb.d/twitter-clone.sql
    ports:
      - 5432:5432
    networks:
      - nginx_network
    environment:
      POSTGRES_USER: peterhartmann
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: twitter-clone

  app:
    image: twitter:latest
    ports:
      - 8080:8080
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - nginx_network
    depends_on:
      - app

networks:
  database1_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  db_data:
